// Errores y excepciones

// Ej.1
let multiply = (a b) => a + b;
let result = multiply(10, 20);
console.log(result);

// Ej.2
let multipl = (a, b) => a + b;
let result = multiply(10, 20);
console.log(result);

// Ej.3
let multiply = (a, b) => a + b;
let result = multiply(10, 20);
console.log(result);

// Ej.4
let multiply = (a, b) => a * b;
let result = multiply(10, 20);
console.log(result);

// Ej.5
console.log('abc');
conole.log('abc');
console.log('abc');

// Ej.6
try {
    console.log('abc');
    conole.log('abc');
} catch (error) {
    console.log(error.message);
}

console.log('El programa continua');
